// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: mysql.user.sql

package models

import (
	"context"
)

const all = `-- name: All :many
select host, user from user
`

func (q *Queries) All(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, all)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.Host, &i.User); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
