version: '3.8'
x-digdag: &digdag
  image: digdag-local:latest
  build:
    context: .
  dns: 8.8.8.8
  depends_on:
    - postgres
  environment:
    AWS_DEFAULT_REGION: ap-northeast-1
    AWS_DEFAULT_OUTPUT: json
    AWS_PAGER:
  restart: always
  volumes:
    - ./config:/home/digdag/config
    - ./projects:/home/digdag/projects
    - ./scripts:/home/digdag/scripts
    - ./shared:/home/digdag/shared
    - ./.secrets:/home/digdag/.secrets
services:
  web:
    <<: *digdag
    command: "java -jar /usr/local/bin/digdag server --disable-executor-loop --disable-local-agent -c /home/digdag/config/server.conf"
    ports:
      - "65432:65432"
      - "65433:65433"
  worker:
    <<: *digdag
    command: "java -jar /usr/local/bin/digdag server -c /home/digdag/config/server.conf"
  minio:
    image: quay.io/minio/minio:latest
    command: "server /data --console-address :9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    restart: always
    volumes:
      - .docker/minio:/data
  postgres:
    image: postgres:14.6-alpine
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    volumes:
      - .docker/pg-data:/var/lib/postgresql/data
