version: '3.8'
services:
  dev:
    image: go-local:latest
    build:
      context: .
      target: dev
    depends_on:
      - mysql
    volumes:
      - .:/opt
  mysql:
    image: mysql:5.7.37
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
    platform: linux/x86_64
    restart: always
    volumes:
      - ./.volumes/mysql:/var/lib/mysql
